MIME_TYPE_BASE = "application/vnd.skotstein.sentence-transformer"
MIME_TYPE_APPLICATION_JSON = "application/json"
MIME_TYPE_TEXT_HTML = "text/html"
MIME_TYPE_APPLICATION_XHTML_XML = "application/xhtml+xml"
MIME_TYPE_ERROR_V1_JSON = MIME_TYPE_BASE+".error.v1+json"
MIME_TYPE_HYPERMEDIA_V1_JSON = MIME_TYPE_BASE+".hypermedia.v1+json"
MIME_TYPE_RESULTS_V1_JSON = MIME_TYPE_BASE+".results.v1+json"
MIME_TYPE_JOBS_V1_JSON = MIME_TYPE_BASE+".jobs.v1+json"